### ISSUE TITLE
Kieran West; stroke footplate rail

### ISSUE THREAD

**Issue by umarndt** [13enedict/CCRC#278]

**Comment by umarndt** [comment]
reported by M4 (we went through and everyone checked their seat)
various issues regarding bad shoes and loose shoes is being fixed by crew. contact @eyal for more details.

**Comment by NSinclair94** [comment]
Try tightening the screw?

**Comment by eyalpole** [comment]
It felt loose, but I'll see if there's a bolt on the other side I could use for tightening (or if it's a wood-screw, in which case no use).

**Comment by eyalpole** [comment]
Back from outing - PROBLEM NOT SOLVED.  the new screw got loose 👎

**Comment by NSinclair94** [comment]
Tighten it

**Comment by eyalpole** [comment]
Back from outing - PROBLEM NOT SOLVED. the new screw is loose 👎

**Comment by NSinclair94** [comment]
Tighten it

**Comment by 13enedict** [comment]
I seem to recall that there's something funny about the adjuster strip channels on KW. On the bow seat, I think I had to put some wood under the deck to screw one or both of the channels down.
